import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {ArrowLeft,LogOut,Search,ShieldCheck,Trash2,UserRound} from 'lucide-react'
import './styles.css'
import {supabase} from './supabase'

type Row={id:string;created_at:string;client_name:string;birth_date:string|null;phone:string;email:string|null;allergies:string;eye_sensitivity:string;contact_lenses:string;recent_eye_issue:string;medications:string;previous_extensions:string;previous_reaction:string;lash_habits:string;brow_procedures:string;recent_skin_procedure:string;skin_sensitivity:string;procedure:string;consent:boolean;privacy:boolean}
function Admin(){const [rows,setRows]=useState<Row[]>([]);const [selected,setSelected]=useState<Row|null>(null);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!supabase){setError('Supabase não configurado.');setLoading(false);return}const {data:user}=await supabase.auth.getUser();if(!user.user){window.location.href='/';return}const {data,error}=await supabase.from('anamnesis').select('*').order('created_at',{ascending:false});if(error)setError(error.message);else setRows(data||[]);setLoading(false)})()},[])
 const filtered=rows.filter(r=>`${r.client_name} ${r.phone} ${r.email||''}`.toLowerCase().includes(search.toLowerCase()))
 async function remove(id:string){if(!confirm('Excluir esta ficha permanentemente?'))return;if(!supabase)return;const {error}=await supabase.from('anamnesis').delete().eq('id',id);if(error){setError(error.message);return}setRows(x=>x.filter(r=>r.id!==id));setSelected(null)}
 async function logout(){await supabase?.auth.signOut();window.location.href='/' }
 return <main className="admin-page"><header className="admin-top"><a href="/" className="brand"><span>ANA</span><small>CARVALHO</small></a><div className="admin-title"><ShieldCheck size={15}/> ÁREA RESTRITA</div><button className="logout" onClick={logout}><LogOut size={16}/> Sair</button></header><section className="admin-shell"><div className="admin-heading"><div><p className="eyebrow"><UserRound size={13}/> ADMINISTRAÇÃO</p><h1>Fichas de <i>anamnese.</i></h1><p>Visualize e acompanhe as fichas enviadas pelas suas clientes.</p></div><a href="/" className="back-site"><ArrowLeft size={16}/> Voltar ao formulário</a></div><div className="admin-card"><div className="list-head"><div><strong>{rows.length}</strong><span>fichas recebidas</span></div><label className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente..."/></label></div>{loading?<div className="empty">Carregando fichas...</div>:error?<div className="error">{error}</div>:filtered.length===0?<div className="empty">Nenhuma ficha encontrada.</div>:<div className="client-list">{filtered.map(r=><button className="client-row" key={r.id} onClick={()=>setSelected(r)}><div className="avatar">{r.client_name.charAt(0).toUpperCase()}</div><div className="client-main"><strong>{r.client_name}</strong><span>{r.phone}</span></div><time>{new Date(r.created_at).toLocaleDateString('pt-BR')}</time></button>)}</div>}</div></section>{selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="detail-modal"><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">FICHA DE ANAMNESE</p><h2>{selected.client_name}</h2><div className="detail-grid"><div><span>Telefone</span><strong>{selected.phone}</strong></div><div><span>E-mail</span><strong>{selected.email||'—'}</strong></div><div><span>Nascimento</span><strong>{selected.birth_date?new Date(selected.birth_date+'T00:00:00').toLocaleDateString('pt-BR'):'—'}</strong></div><div><span>Procedimento</span><strong>{selected.procedure||'—'}</strong></div></div><div className="answers"><h3>Saúde & segurança</h3>{[['Alergia',selected.allergies],['Sensibilidade ocular',selected.eye_sensitivity],['Lentes de contato',selected.contact_lenses],['Problema ocular recente',selected.recent_eye_issue],['Medicamentos',selected.medications],['Extensão anterior',selected.previous_extensions],['Reação anterior',selected.previous_reaction],['Hábito de esfregar/puxar cílios',selected.lash_habits],['Procedimentos nas sobrancelhas',selected.brow_procedures],['Procedimento recente na pele',selected.recent_skin_procedure],['Sensibilidade da pele',selected.skin_sensitivity]].map(([l,v])=><div key={l as string}><span>{l}</span><strong>{v||'—'}</strong></div>)}</div><button className="delete-btn" onClick={()=>remove(selected.id)}><Trash2 size={16}/> Excluir ficha</button></div></div>}</main>}
createRoot(document.getElementById('root')!).render(<Admin/>)
