import React, { FormEvent, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Check, ChevronLeft, ChevronRight, FileText, LockKeyhole, LogIn, Menu, ShieldCheck, Sparkles, X } from 'lucide-react'
import './styles.css'
import { supabase } from './supabase'

type FormData = {
  name: string; birth_date: string; phone: string; email: string
  allergies: string; eye_sensitivity: string; contact_lenses: string; recent_eye_issue: string; medications: string
  previous_extensions: string; previous_reaction: string; lash_habits: string
  brow_procedures: string; recent_skin_procedure: string; skin_sensitivity: string
  desired_result: string; procedure: string; observations: string; consent: boolean; privacy: boolean
}
const initial: FormData = {name:'',birth_date:'',phone:'',email:'',allergies:'',eye_sensitivity:'',contact_lenses:'',recent_eye_issue:'',medications:'',previous_extensions:'',previous_reaction:'',lash_habits:'',brow_procedures:'',recent_skin_procedure:'',skin_sensitivity:'',desired_result:'',procedure:'',observations:'',consent:false,privacy:false}
const steps=[['01','Dados pessoais','Quem é você?'],['02','Saúde & segurança','Responda apenas o que se aplica'],['03','Histórico de cílios','Seu histórico'],['04','Sobrancelhas','Pele e procedimentos'],['05','Finalização','Preferências e consentimento']]
const yesNo=[{key:'allergies',label:'Você possui alguma alergia conhecida?'},{key:'eye_sensitivity',label:'Você possui sensibilidade ou desconforto nos olhos?'},{key:'contact_lenses',label:'Você usa lentes de contato?'},{key:'recent_eye_issue',label:'Teve irritação, infecção ou procedimento ocular recentemente?'},{key:'medications',label:'Você faz uso de algum medicamento que possa ser relevante para o atendimento?'}]
function Field({label,children,required=false}:{label:string;children:React.ReactNode;required?:boolean}){return <label className="field"><span>{label}{required&&<b>*</b>}</span>{children}</label>}
function Text({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder||''}/>} 
function Choice({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="choices"><button type="button" className={value==='sim'?'selected':''} onClick={()=>onChange('sim')}>Sim</button><button type="button" className={value==='nao'?'selected':''} onClick={()=>onChange('nao')}>Não</button></div>}
function DateSelect({value,onChange}:{value:string;onChange:(v:string)=>void}){const [y,m,d]=value?value.split('-'):['','',''];const years=Array.from({length:100},(_,i)=>String(new Date().getFullYear()-i));const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];const days=Array.from({length:31},(_,i)=>String(i+1).padStart(2,'0'));const update=(part:string,v:string)=>{const next={y,m,d};(next as any)[part]=v;if(next.y&&next.m&&next.d)onChange(`${next.y}-${next.m}-${next.d}`);else onChange('')};return <div className="date-grid"><select value={d} onChange={e=>update('d',e.target.value)}><option value="">Dia</option>{days.map(x=><option key={x} value={x}>{x}</option>)}</select><select value={m} onChange={e=>update('m',e.target.value)}><option value="">Mês</option>{months.map((x,i)=><option key={x} value={String(i+1).padStart(2,'0')}>{x}</option>)}</select><select value={y} onChange={e=>update('y',e.target.value)}><option value="">Ano</option>{years.map(x=><option key={x} value={x}>{x}</option>)}</select></div>}
function App(){
 const [step,setStep]=useState(0); const [data,setData]=useState<FormData>(initial); const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [adminOpen,setAdminOpen]=useState(false); const [mobileMenu,setMobileMenu]=useState(false); const [adminUser,setAdminUser]=useState(''); const [adminPassword,setAdminPassword]=useState(''); const [adminLoading,setAdminLoading]=useState(false); const [adminError,setAdminError]=useState('');
 const set=(k:keyof FormData)=>(v:string|boolean)=>setData(d=>({...d,[k]:v}));
 const valid=useMemo(()=>{if(step===0)return !!(data.name.trim()&&data.phone.trim()); if(step===1)return yesNo.every(q=>!!data[q.key as keyof FormData]); if(step===4)return data.consent&&data.privacy; return true},[step,data]);
 async function submit(e:FormEvent){e.preventDefault();if(!valid)return;setLoading(true);setError('');try{if(!supabase)throw new Error('A conexão com o Supabase ainda não foi configurada.');const {error}=await supabase.from('anamnesis').insert({client_name:data.name,birth_date:data.birth_date||null,phone:data.phone,email:data.email||null,allergies:data.allergies,eye_sensitivity:data.eye_sensitivity,contact_lenses:data.contact_lenses,recent_eye_issue:data.recent_eye_issue,medications:data.medications,previous_extensions:data.previous_extensions,previous_reaction:data.previous_reaction,lash_habits:data.lash_habits,brow_procedures:data.brow_procedures,recent_skin_procedure:data.recent_skin_procedure,skin_sensitivity:data.skin_sensitivity,desired_result:data.desired_result,procedure:data.procedure,observations:data.observations,consent:data.consent,privacy:data.privacy});if(error)throw error;setSent(true)}catch(err){setError(err instanceof Error?err.message:'Não foi possível enviar sua ficha.')}finally{setLoading(false)}}
 async function login(e:FormEvent){e.preventDefault();setAdminLoading(true);setAdminError('');try{if(!supabase)throw new Error('Supabase ainda não configurado.');const {data:lookup,error:lookupError}=await supabase.rpc('get_admin_email',{p_username:adminUser.trim()});if(lookupError)throw lookupError;if(!lookup)throw new Error('Usuário ou senha inválidos.');const {error}=await supabase.auth.signInWithPassword({email:lookup,password:adminPassword});if(error)throw new Error('Usuário ou senha inválidos.');window.location.href='/admin'}catch(err){setAdminError(err instanceof Error?err.message:'Usuário ou senha inválidos.')}finally{setAdminLoading(false)}}
 if(sent)return <main className="success"><div className="success-card"><div className="mark"><Check/></div><p className="eyebrow">ANA CARVALHO · BEAUTY</p><h1>Ficha recebida<br/><i>com sucesso.</i></h1><p>Obrigada por preencher sua anamnese. Suas informações foram enviadas com segurança e serão consideradas antes do seu atendimento.</p><div className="privacy"><LockKeyhole size={16}/> Seus dados são tratados de forma reservada.</div></div></main>
 return <main><header className="top"><a className="brand" href="/"><span>ANA</span><small>CARVALHO</small></a><div className="desktop-admin"><button className="restricted" onClick={()=>setAdminOpen(true)}><ShieldCheck size={15}/> Área restrita</button></div><button className="mobile-menu" onClick={()=>setMobileMenu(v=>!v)} aria-label="Abrir menu">{mobileMenu?<X size={20}/>:<Menu size={20}/>}</button>{mobileMenu&&<div className="mobile-panel"><button onClick={()=>{setAdminOpen(true);setMobileMenu(false)}}><ShieldCheck size={16}/> Área restrita</button></div>}</header>
 <section className="hero"><div className="eyebrow"><Sparkles size={13}/> ANAMNESE · BEAUTY</div><h1>Antes de cuidar da sua beleza,<br/><i>quero conhecer você.</i></h1><p>Preencha sua ficha com calma. Essas informações ajudam a tornar seu atendimento mais seguro, personalizado e especial.</p></section>
 <section className="progress">{steps.map((s,i)=><div className={i===step?'active':''} key={s[0]}><em>{s[0]}</em><span>{s[1]}</span></div>)}</section>
 <form onSubmit={submit} className="form"><div className="section-head"><span>{steps[step][0]}</span><div><p>{steps[step][1]}</p><h2>{steps[step][2]}</h2></div></div>
 {step===0&&<div className="grid"><Field label="Nome completo" required><Text value={data.name} onChange={set('name')} placeholder="Seu nome"/></Field><Field label="Data de nascimento"><DateSelect value={data.birth_date} onChange={set('birth_date')}/></Field><Field label="WhatsApp / telefone" required><Text value={data.phone} onChange={set('phone')} placeholder="(00) 00000-0000"/></Field><Field label="E-mail"><Text value={data.email} onChange={set('email')} placeholder="voce@email.com"/></Field></div>}
 {step===1&&<div className="choice-list">{yesNo.map(q=><div className="choice-row" key={q.key}><div><strong>{q.label}</strong><small>Selecione uma opção</small></div><Choice value={String(data[q.key as keyof FormData])} onChange={set(q.key as keyof FormData)}/></div>)}</div>}
 {step===2&&<div className="stack"><Field label="Já realizou extensão de cílios anteriormente?"><Choice value={data.previous_extensions} onChange={set('previous_extensions')}/></Field><Field label="Já teve alguma reação ou desconforto em procedimento anterior?"><Choice value={data.previous_reaction} onChange={set('previous_reaction')}/></Field><Field label="Você costuma esfregar ou puxar os cílios?"><Choice value={data.lash_habits} onChange={set('lash_habits')}/></Field></div>}
 {step===3&&<div className="stack"><Field label="Já realizou procedimentos nas sobrancelhas?"><Choice value={data.brow_procedures} onChange={set('brow_procedures')}/></Field><Field label="Realizou algum procedimento recente na pele da região?"><Choice value={data.recent_skin_procedure} onChange={set('recent_skin_procedure')}/></Field><Field label="Sua pele apresenta sensibilidade ou costuma reagir a produtos?"><Choice value={data.skin_sensitivity} onChange={set('skin_sensitivity')}/></Field></div>}
 {step===4&&<div className="stack"><Field label="Qual procedimento será realizado?"><div className="procedure-options"><button type="button" className={data.procedure==='Extensão de cílios'?'selected':''} onClick={()=>set('procedure')('Extensão de cílios')}>Extensão de cílios</button><button type="button" className={data.procedure==='Design de sobrancelhas'?'selected':''} onClick={()=>set('procedure')('Design de sobrancelhas')}>Design de sobrancelhas</button><button type="button" className={data.procedure==='Outro'?'selected':''} onClick={()=>set('procedure')('Outro')}>Outro</button></div></Field><div className="checks"><label><input type="checkbox" checked={data.consent} onChange={e=>set('consent')(e.target.checked)}/><span>Declaro que as informações fornecidas são verdadeiras e autorizo a realização do atendimento de acordo com as informações prestadas.</span></label><label><input type="checkbox" checked={data.privacy} onChange={e=>set('privacy')(e.target.checked)}/><span>Estou ciente de que meus dados serão utilizados para fins relacionados ao meu atendimento e tratados de forma confidencial.</span></label></div></div>}
 {error&&<div className="error">{error}</div>}<div className="actions">{step>0&&<button type="button" className="back" onClick={()=>setStep(s=>s-1)}><ChevronLeft size={18}/> Voltar</button>}<button type={step===4?'submit':'button'} disabled={!valid||loading} onClick={()=>step<4&&setStep(s=>s+1)}>{loading?'Enviando...':step===4?'Enviar minha ficha':'Continuar'}{step<4&&<ChevronRight size={18}/>}</button></div></form><footer><FileText size={16}/> ANA CARVALHO · EXTENSÃO DE CÍLIOS & SOBRANCELHAS</footer>
 {adminOpen&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setAdminOpen(false)}><div className="login-modal"><button className="close" onClick={()=>setAdminOpen(false)}><X size={18}/></button><div className="modal-icon"><LogIn size={19}/></div><p className="eyebrow">ACESSO PRIVADO</p><h2>Área <i>restrita.</i></h2><p className="modal-copy">Acesso exclusivo para administração da Ana Carvalho.</p><form onSubmit={login}><Field label="Usuário"><input value={adminUser} onChange={e=>setAdminUser(e.target.value)} autoComplete="username"/></Field><Field label="Senha"><input type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} autoComplete="current-password"/></Field>{adminError&&<div className="error">{adminError}</div>}<button className="login-submit" disabled={adminLoading}>{adminLoading?'Entrando...':'Entrar na área restrita'}<ChevronRight size={17}/></button></form></div></div>}
 </main>
}
if (window.location.pathname === '/admin') { import('./admin').catch(() => { window.location.href='/' }) } else { createRoot(document.getElementById('root')!).render(<App/>) }
